# fly.toml app configuration file generated for restless-butterfly-4927 on 2023-10-24T14:56:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restless-butterfly-4927"
primary_region = "dfw"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run migrate up"